### PR TITLE
Implement fs module

### PR DESCRIPTION
**Pull request by sajattack**
Unresolved:
- relative paths
- dirent path

### CODE REVIEW

**Comment by sajattack** [comment]
Wtf did git do?

**Comment by MrAwesome** [comment]
Ah I missed this - ready for me to merge it into the branch? I can go through and resolve the merge conflicts if so.

**Comment by sajattack** [comment]
Yeah it just needs to be properly merged with the fd stuff.

**Comment by sajattack** [comment]
I figured out how to get the directory the program is launched from so I'll probably do cwd before we merge this.

**Comment by sajattack** [comment]
superceded by #4

**Pull request closed without merging**
